### PR TITLE
Feature/criacao entidade dto

### PR DESCRIPTION
**Pull request by DanielRodrigoBeltrame**

### CODE REVIEW

**Comment by DanielRodrigoBeltrame** [comment]
[05 - Criar entidade de FORM](https://trello.com/c/V7yhd0Rs/22-05-criar-entidade-de-form)

**Comment by DanielRodrigoBeltrame** [comment]
[06 - Criar DTO de Response para FORM](https://trello.com/c/XY0BrWsW/30-06-criar-dto-de-response-para-form)

**Comment by DanielRodrigoBeltrame** [comment]
[07 - Criar DTO de Request para FORM](https://trello.com/c/guJe3t0D/31-07-criar-dto-de-request-para-form)

**Comment by DanielRodrigoBeltrame** [comment]
[09 - Criar DTO de Request para CUSTOMER](https://trello.com/c/Ws7RFCyO/27-09-criar-dto-de-request-para-customer)

**Comment by DanielRodrigoBeltrame** [comment]
[08 - Criar DTO de Response para CUSTOMER](https://trello.com/c/H4jfPZcQ/26-08-criar-dto-de-response-para-customer)

**Comment by DanielRodrigoBeltrame** [comment]
[10 - Criar DTO de Response para CONSULTANT](https://trello.com/c/QfegnfBu/28-10-criar-dto-de-response-para-consultant)

**Comment by DanielRodrigoBeltrame** [comment]
[11 - Criar DTO de Request para CONSULTANT](https://trello.com/c/m2lzG52f/29-11-criar-dto-de-request-para-consultant)

**Comment by DanielRodrigoBeltrame** [comment]
[21 - Criar DTO de Response para Contact](https://trello.com/c/8WS6ZFKD/42-21-criar-dto-de-response-para-contact)

**Comment by DanielRodrigoBeltrame** [comment]
[22 - Criar DTO de Request para Contact](https://trello.com/c/OLiGsKpt/43-22-criar-dto-de-request-para-contact)

**Review by ClovisPilgerJunior — APPROVED** [review]

**Pull request merged**
